# permissions for end users to edit petclinics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: petclinic-editor-role
rules:
- apiGroups:
  - example.njtech.edu.cn
  resources:
  - petclinics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.njtech.edu.cn
  resources:
  - petclinics/status
  verbs:
  - get
