---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - example.njtech.edu.cn
  resources:
  - petclinics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.njtech.edu.cn
  resources:
  - petclinics/finalizers
  verbs:
  - update
- apiGroups:
  - example.njtech.edu.cn
  resources:
  - petclinics/status
  verbs:
  - get
  - patch
  - update
